services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    env_file:
      - frontend/.env.development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '8080:8080'
    env_file:
      - backend/.env.development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    env_file:
      - backend/.env.development
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  pg-data:

networks:
  app-network:
    driver: bridge
